class FOD(object):
    ID = "ID"
    NAME = "Name"
    AGE = "Age"
    NATIONALITY = "Nationality"
    OVERALL = "Overall"
    POTENTIAL = "Potential"
    CLUB = "Club"
    VALUE = "Value"
    WAGE = "Wage"
    SPECIAL = "Special"
    PREFERRED_FOOT = "Preferred Foot"
    INTERNATIONAL_REPUTATION = "International Reputation"
    WEAK_FOOT = "Weak Foot"
    SKILL_MOVES = "Skill Moves"
    WORK_RATE = "Work Rate"
    BODY_TYPE = "Body Type"
    REAL_FACE = "Real Face"
    POSITION = "Position"
    JOINED = "Joined"
    LOANED_FROM = "Loaned From"
    CONTRACT_VALID_UNTIL = "Contract Valid Until"
    HEIGHT = "Height"
    WEIGHT = "Weight"
    RELEASE_CLAUSE = "Release Clause"
    KIT_NUMBER = "Kit Number"
    ROLE = "Role"
    NUMBER_OF_PLAYERS_ON_LOAN = "Number of Players on loan"

    PHOTO = "Photo"
    FLAG = "Flag"
    CLUB_LOGO = "Club Logo"
    BEST_OVER_ALL_RATING = "Best Overall Rating"


class FC():
    COUNTRY = "Country"
    CLUB = "Club"
